#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs zed onto your system into ~/.local, making it available as ~/.local/bin/zed.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export ZED_CHANNEL=$(<crates/zed/RELEASE_CHANNEL)
export ZED_UPDATE_EXPLANATION="You need to fetch and rebuild zed in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="zed-linux-${arch}.tar.gz"
export ZED_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh

suffix=""
if [[ "$ZED_CHANNEL" != "stable" ]]; then
  suffix="-$ZED_CHANNEL"
fi
server_archive="${CARGO_TARGET_DIR:-target}/zed-remote-server-linux-${arch}.gz"
installed_libexec="$HOME/.local/zed${suffix}.app/libexec"
cp "$server_archive" "$installed_libexec/"
sha256sum "$server_archive" | cut -d ' ' -f 1 > "$installed_libexec/zed-remote-server-local-build"
